spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${cognitive-exercises-frontend-host}
            allowedMethods: "*"
            allowedHeaders: "*"